image: node:12.13.0
pipelines:
  branches:
    master:
      - step:
          script:
            - node --version
            - npm install -g serverless
            - npm install
            - cd functions && npm install && cd ..
            - serverless config credentials --stage prod --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - serverless deploy --stage prod
    homologation:
      - step:
          script:
            - node --version
            - npm install -g serverless
            - npm install
            - cd functions && npm install && cd ..
            - serverless config credentials --stage qa --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - serverless deploy --stage qa
    development:
      - step:
          script:
            - node --version
            - npm install -g serverless
            - npm install
            - cd functions && npm install && cd ..
            - serverless config credentials --stage dev --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - serverless deploy --stage dev
